### PR TITLE
Redesign Using Tailwindcss.

### PR DESCRIPTION
**Pull request by osamamhd**

### CODE REVIEW

**Comment by RohanJnr** [comment]
Can you share a few screenshots of the changes made?

**Comment by osamamhd** [comment]
I didn't start yet, I just want to show you the idea of redesign the pages using Tailwindcss, I want to know your opinion.

**Comment by RohanJnr** [comment]
I am planning to build the frontend using a framework soon, react or vue, not sure I would want to redeisgn the frontend now

**Comment by osamamhd** [comment]
Okay.

**Pull request closed without merging**
